services:
  prod:
    profiles:
      - prod
    image: ghcr.io/shadowkudo/ctfman:latest
    build:
      context: .
      target: prod
    ports:
      - "${SERVER_ADDRESS:-127.0.0.1}:${SERVER_PORT:-8080}:80"
    command: "--port 80 --address 0.0.0.0"
  dev:
    profiles:
      - dev
    build:
      context: .
      target: dev
    volumes:
      - ".:/app"
    ports:
      - "${SERVER_ADDRESS:-127.0.0.1}:${SERVER_PORT:-8080}:8080"
    command: "--port 8080 --address 0.0.0.0"
  db:
    profiles:
      - prod
      - dev
    image: bitnami/postgresql:17
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRESQL_USERNAME: "${PG_USER:-ctfman}"
      POSTGRESQL_PASSWORD: "${PG_PASS:-ctfman}"
      POSTGRESQL_DATABASE: "${PG_DB:-ctfman}"
      POSTGRESQL_POSTGRES_PASSWORD: "${PG_ROOT_PASS:-root}"
    volumes:
      - pgdata:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
